version: "3.8"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    ports:
      - 1433:1433
    environment:
      - SA_PASSWORD=Very-Complex-Password
      - ACCEPT_EULA=Y
      - MSSQL_AGENT_ENABLED=true
      - TZ=UTC
